POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ha2tlIiwiaWQiOiI1ZjFjMjFhMmIyNzkwMDkzOGU2ODMwNDkiLCJpYXQiOjE2MDM4NzIwMTF9.tcaQC3_9-PjrTfRvdKpQRT0neyu2PkYcTOSyBFjCOYc

{
  "title": "hihhiii",
  "author": "Hell Yeah",
  "url": "www.ohyeah.com",
  "likes": 300563
} 