POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZjE4NjY3MzdlNTU4YzY5ODVjYWE1NzMiLCJpYXQiOjE1OTU2ODU0NzJ9._ma9io1pd8Vl0q-1Dmeve05A_uFNU1US2hxURQ8wHp0

{
  "title": "Oh no",
  "author": "Hell Yeah",
  "url": "www.ohyeah.com",
  "likes": 300563
} 